Django Project/accounts/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path
from .views import dashboard,register,logout,login,ProfileUpdateView,password_reset_request

from django.contrib.auth.views import LogoutView
from appSale import views as appSaleViews
from django.contrib.auth.decorators import login_required

from .views import (ProfileUpdateView)

urlpatterns = [
    # path('login/', login_view, name="login"),
    # path("logout/", LogoutView.as_view(), name="logout"),
    
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout, name='logout'),
    path('dashboard', dashboard, name='dashboard'),
    path('profile/<int:pk>', login_required(
         ProfileUpdateView.as_view()), name='profile'),
    path("password-reset", password_reset_request, name="password-reset")
    
]

Django Project/contacts/urls.py
from django.urls import path
from .views import (anonymous_contact, user_contact, chat_message,
                    MessageHistoryListView)


urlpatterns = [
    path('anonymous-contact', anonymous_contact, name='anonymous-contact'),
    path('user-contact', user_contact, name='user-contact'),
    path('chat', chat_message, name='chat'),
    path('history/<int:pk>', MessageHistoryListView.as_view(), name='chat-history'),
]

Django Project/moviereviews/urls.py
from zipfile import Path
from django.contrib import admin
from django.urls import path , include
from appSale import views as appSaleViews
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf import settings
from contacts.views import AdminContactView

urlpatterns =[
    path('admin/', admin.site.urls),
   # path('',appSaleViews.home ,name='home'), 
    path('', appSaleViews.index, name='index'),
    path('', appSaleViews.index, name='indexList'),
    path('about/',appSaleViews.about, name='about'),
    path('house/',appSaleViews.house, name='house'),
    path('price/',appSaleViews.price, name='price'),
    path('contact/',appSaleViews.contact, name='contact'),
   
    path('subscribe/',appSaleViews.subscribe, name='subscribe'),

    #path('signup/',appSaleViews.signup, name='signup'),
    #path('accounts/', include('accounts.urls'))
    path("", include('accounts.urls')),

    path('listings/', include('listings.urls')),
    path('contacts/', include('contacts.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    # path('admin/', admin.site.urls),
    path('admin/contact/', AdminContactView.as_view(), name='admin-contact'),
    
    
     path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/auth/password_reset_done.html'),
         name='password-reset-done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(  # noqa
        template_name="accounts/auth/password_reset_confirm.html"),
         name='password-reset-confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/auth/password_reset_complete.html'),
         name='password_reset_complete'),
    
    
        
]

urlpatterns += static(settings.MEDIA_URL,
 document_root=settings.MEDIA_ROOT)

Django Project/contacts/models.py
from django.db import models
from datetime import datetime
from django.conf import settings
from django.utils.translation import gettext_lazy as _



class Contact(models.Model):
    listing = models.ForeignKey('listings.Listing',
                                on_delete=models.DO_NOTHING,
                                verbose_name=_("Listing"))
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.PROTECT, verbose_name=_("User"))
    phone = models.CharField(max_length=100, verbose_name=_("Phone"))
    message = models.TextField(blank=True, verbose_name=_("Message"))
    contact_date = models.DateTimeField(default=datetime.now, blank=True,
                                        verbose_name=_("Contact date"))
    can_access_documents = models.BooleanField(default=False,
                                               verbose_name=_("Docs access"))

    

    def get_full_name(self):
        return f"{self.user.first_name} {self.user.last_name}"
    get_full_name.short_description = _("Client")

    def get_email(self):
        return f"{self.user.email}"
    get_email.short_description = _("Email")
    
    
    
    
    class Meta:
        ordering = ['-contact_date']

    def __str__(self):
        return f"{self.listing}"


    
class ChatMessage(models.Model):
    contact = models.ForeignKey(Contact, on_delete=models.PROTECT,
                                verbose_name=_("Contact listing"))
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.PROTECT, verbose_name=_("User"))
    message = models.TextField(null=True, blank=False)
    timestamp = models.DateTimeField(default=datetime.now, blank=True,
                                     verbose_name=_("Date and iime"))

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return f"{self.contact} - {self.user} - {self.message}"

Django Project/appSale/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django.utils.translation import gettext_lazy as _

Django Project/appSale/views.py
from re import search
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.urls import path,include
from appSale.models import housesale,Users,Price,House_Category,Realtor_Menu,ContactForm
from django.contrib.auth.decorators import login_required
from django.views.generic import (TemplateView)
from django.utils.translation import gettext_lazy as _

from appSale.models import State
from listings.models import Listing, ListingType
from accounts.models import Realtor



# def index(request):
#   house=housesale.objects.all()
#   price=Price.objects.all() 

  
#   return render(request, 'index.html',{'house':house,'price':price}) 


def index(request):
  listings=Listing.objects.order_by('-created').filter(is_published=True)[:9]
  states=State.objects.all()
  list_types=ListingType.objects.all()
  price=Price.objects.all() 
  realtor_menu=Realtor_Menu.objects.all()

  
  return render(request, 'index.html',{'listings':listings,'states':states,'list_types':list_types,'price':price,'realtor_menu':realtor_menu}) 







class indexList(TemplateView):
    template_name = 'templates/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['listings'] = Listing.objects.order_by('-created').filter(
                               is_published=True)[:3]
        context['states'] = State.objects.all()
        context['list_types'] = ListingType.objects.all()
        context['index'] = True
        # SEO
        context['page_title'] = _("Real estate manager."
                                  " Renting, buying and selling.")
        context['page_description'] = _("Real estate manager. We offer"
                                        " real estate objects and takes care"
                                        " of every aspect for you. Services"
                                        " offered: renting, selling, buying,"
                                        " consultation and way more.")
        return context




def about(request):
  return render(request, 'about.html')

def subscribe(request):
  return render(request, 'subscribe.html')
def house(request):
  house=housesale.objects.all()
  return render(request, 'house.html',{'house':house})
def price(request):
  price=Price.objects.all()
  return render(request, 'price.html',{'price':price})

def contact(request):
      if request.method == 'POST':
        contact=ContactForm()
        c_name = request.POST.get('c_name')
        c_email = request.POST.get('c_email')
        c_phone = request.POST.get('c_phone')
        c_message = request.POST.get('c_message')
        a1=('contact.html')
        a2=('email.html')
        contact.contact_name=c_name
        contact.contact_email=c_email
        contact.contact_phone=c_phone
        contact.contact_messages=c_message
        contact.save()
        

      return render(request, 'contact.html')
    

    


@login_required(login_url="/login/")

# def home(request):  
#     searchTerm = request.GET.get('searchMovie')
#     return render(request, 'home.html',{'searchTerm':searchTerm})

def signup(request):
    email = request.GET.get('email')
    return render(request, 'signup.html', {'email':email})


# Create your views here.

Django Project/contacts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.mail import send_mail
from .models import Contact, ChatMessage
from django.contrib.auth.decorators import login_required
from django.utils.translation import gettext_lazy as _
from django.core.paginator import Paginator
from django.views.generic import (DetailView, TemplateView)
from listings.models import Listing
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse

def user_contact(request):
    if request.method == 'POST':
        listing_id = request.POST['listing_id']
        phone = request.POST['phone']
        message = request.POST['message']
        user_id = request.POST['user_id']
        realtor_email = request.POST['realtor_email']

        #  Check if user has made inquiry already
        if request.user.is_authenticated:
            user_id = request.user.id
            has_contacted = Contact.objects.all().filter(
                listing_id=listing_id, user_id=user_id)
            if has_contacted:
                messages.error(
                    request, _("You have already made an inquiry "
                               "for this listing"))
                return redirect('listing', listing_id)

        contact = Contact(listing_id=listing_id, phone=phone, message=message,
                          user_id=user_id)

        contact.save()

        # Send email
        send_mail(f'Property Listing Inquiry',
                  f'There has been an inquiry for '
                  f'{Listing.objects.get(id=listing_id)}'
                  f'. Sign into the admin panel for more info',
                  'schonefeld.dev@gmail.com',
                  [realtor_email, 'schonefeld.dev@gmail.com'],
                  fail_silently=False)

        messages.success(
            request, (_("Your request has been submitted, a realtor will "
                        "get back to you soon")))
        return redirect('/listings/' + listing_id)


def anonymous_contact(request):
    if request.method == 'POST':
        listing_id = request.POST['listing_id']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        phone = request.POST['phone']
        message = request.POST['message']
        realtor_email = request.POST['realtor_email']

        #  Check if user has made inquiry already
        if request.user.is_authenticated:
            user_id = request.user.id
            has_contacted = Contact.objects.all().filter(
                listing_id=listing_id, first_name=first_name,
                last_name=last_name)
            if has_contacted:
                messages.error(
                    request, _("You have already made an inquiry for this "
                               "listing"))
                return redirect('listing', pk=listing_id)

        contact = Contact(listing_id=listing_id, phone=phone, message=message,
                          user_id=user_id)

        contact.save()

        # Send email
        send_mail('Property Listing Inquiry',
                  'There has been an inquiry for '
                  + Listing.object.get(id=listing_id)
                  + '. Sign into the admin panel for more info',
                  'schonefeld.dev@gmail.com',
                  [realtor_email, 'schonefeld.dev@gmail.com'],
                  fail_silently=False)

        messages.success(
            request, (_("Your request has been submitted, a realtor will "
                        "get back to you soon")))
        return redirect('/listings/' + listing_id)


@login_required
def chat_message(request):
    if request.method == 'POST':
        contact_id = request.POST['contact_id']
        user_id = request.POST['user_id']
        message = request.POST['message']

        obj = ChatMessage(contact_id=contact_id, message=message,
                          user_id=user_id)

        obj.save()

        messages.success(
            request, (_("Your request has been submitted, a realtor will ' \
                        'get back to you soon")))
        return redirect('chat-history', pk=contact_id)


class MessageHistoryListView(DetailView):
    model = Contact
    template_name = 'contacts/messages_history.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Showcase Section Infos
        context['title'] = _("Message History")
        context['subtitle'] = self.object.listing.title
        # SEO
        context['page_title'] = _("Message History")
        context['page_description'] = _("Real estate manager."
                                        "Here you can follow your message "
                                        "history, related to a specific "
                                        "listing you are interested in..")
        return context


class AdminContactView(TemplateView):
    # TODO finish this crap
    template_name = 'admin/contact.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['contact'] = Contact.objects.get(id=5)
        return context

Django Project/appSale/templates/contacts/messages_history.html
{% comment %} {% extends 'core/base.html' %} {% endcomment %}
{% load static %}
{% load crispy_forms_tags %}



<html>
  <head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />
  
    <title>Teaser</title>
  
    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css'%}" />
  
  
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,700|Raleway:400,700&display=swap" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/listings-admin.css'%}" rel="stylesheet" />
    <link href="{% static 'css/listings-all.css'%}" rel="stylesheet" />
    <link href="{% static 'css/listings-lightbox.min.css'%}" rel="stylesheet" />
    <link href="{% static 'css/listings-style.css'%}" rel="stylesheet" />

    <link href="{% static 'css/style.css'%}" rel="stylesheet" />
    
   
    <link href="{% static 'css/responsive.css'%}" rel="stylesheet" />
  
  
  
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.css">
    
  </head>








{% block content %}

<body class="sub_page">

  {% include 'layouts/_header2.html' %}

<section id="showcase-inner" class="py-5 text-white">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-12">
        <h1 class="display-4" style="margin-top:100px; font-weight:bold;">{{ _("Message History") }}</h1>
      </div>
    </div>
  </div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
  <div class="container">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'index' %}">
            <i class="fas fa-home"></i>
            {{ _("Home") }}
          </a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'dashboard' %}">
            {{ _("Dashboard") }}
          </a>
        </li>
        <li class="breadcrumb-item active"> {{ _("History") }}</li>

      </ol>
    </nav>
  </div>
</section>

<!-- Alerts -->
{% include 'layouts/_alerts.html' %}

<section id="dashboard" class="py-4">
  <div class="container">

    <div>
      {% if user.is_authenticated %}
      {% if object.user.id == user.id %}


      <div class="card mb-4">
        <div class="card-header">{{ _("Send new message") }}</div>
        <form action="{% url 'chat' %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="user_id" value="{{ user.id }}">
          <input type="hidden" name="contact_id" value="{{ object.id }}">

          <div class="form-group pl-2 pr-2 pt-2">

            <textarea name="message" class="form-control" rows="4" placeholder='{{ _("Enter message here please...") }}'
              required></textarea>

            <div class="row mt-2 mb-2">
              <div class="col-12 col-lg-6">
                <input type="submit" value="Send" class="btn btn-block btn-secondary">
              </div>
              <div class="col-12 col-lg-6">
                <button type="button" class="btn btn-outline-secondary btn-block"
                  onclick="history.back()">{{ _("Go back") }}</button>
              </div>

            </div>
          </div>

        </form>
      </div>


      <div>
        <h2 class="text-center mb-5 mt-5">{{_("History") }}</h2>
      </div>

      <div>
        {% for message in object.chatmessage_set.all %}


        <div class="row {% if message.user.id == user.id%} chat-right 
                      {% else %} chat-left {% endif %} ml-0 mr-0">

          <div class="row col-md-4">
            <p class="col-12 mt-3 ml-3">{{ message.user.first_name }} {{ message.user.last_name }}</p>
            <small class="col-12 mb-3 ml-3 smaller-things">{{ message.timestamp }} </small>

          </div>
          <div class="col-md-8 vertical-center">
            <p class="pt-3 ml-3">{{ message.message }}</p>
          </div>

        </div>

        {% endfor %}
        {% else %}
        {{ _("Nothing to display") }}
        {% endif %}
      </div>

    </div>
  </div>
</section>
{% endif %}

{% include 'layouts/_footer.html' %}


</body>

</body>
{% endblock %}

<script src="https://maps.googleapis.com/maps/api/js?key=[YOUR-API-KEY]&callback=myMap"></script>
<script type="text/javascript" src="{% static 'js/listings-bootstrap.bundle.min.js' %}"></script> 
<script type="text/javascript" src="{% static 'js/listings-jquery-3.3.1.min.js' %}"></script> 
<script type="text/javascript" src="{% static 'js/listings-jquery-3.3.1.min.js' %}"></script> 
<script type="text/javascript" src="{% static 'js/listings-lightbox.min.js' %}"></script> 
<script type="text/javascript" src="{% static 'js/listings-main.min.js' %}"></script> 

<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script> 
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script> 
<script type="text/javascript" src="{% static 'js/custom.js' %}"></script> 

</html>