Django Project/accounts/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path
from .views import dashboard,register,logout,login,ProfileUpdateView,password_reset_request

from django.contrib.auth.views import LogoutView
from appSale import views as appSaleViews
from django.contrib.auth.decorators import login_required

from .views import (ProfileUpdateView)

urlpatterns = [
    # path('login/', login_view, name="login"),
    # path("logout/", LogoutView.as_view(), name="logout"),
    
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout, name='logout'),
    path('dashboard', dashboard, name='dashboard'),
    path('profile/<int:pk>', login_required(
         ProfileUpdateView.as_view()), name='profile'),
    path("password-reset", password_reset_request, name="password-reset")
    
]

Django Project/documents/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import (ListingDocumentView, UserDocumentView)


urlpatterns = [
    path('<int:pk>/docs/', ListingDocumentView.as_view(), name='documents'),
    path('profile/', login_required(UserDocumentView.as_view()),
         name='user-docs'),
]

Django Project/moviereviews/urls.py
from zipfile import Path
from django.contrib import admin
from django.urls import path , include
from appSale import views as appSaleViews
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf import settings
from contacts.views import AdminContactView

urlpatterns =[
    path('admin/', admin.site.urls),
   # path('',appSaleViews.home ,name='home'), 
    path('', appSaleViews.index, name='index'),
    path('', appSaleViews.index, name='indexList'),
    path('about/',appSaleViews.about, name='about'),
    path('house/',appSaleViews.house, name='house'),
    path('price/',appSaleViews.price, name='price'),
    path('contact/',appSaleViews.contact, name='contact'),
   
    path('subscribe/',appSaleViews.subscribe, name='subscribe'),

    #path('signup/',appSaleViews.signup, name='signup'),
    #path('accounts/', include('accounts.urls'))
    path("", include('accounts.urls')),

    path('listings/', include('listings.urls')),
    path('contacts/', include('contacts.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    # path('admin/', admin.site.urls),
    path('admin/contact/', AdminContactView.as_view(), name='admin-contact'),
    
    
     path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/auth/password_reset_done.html'),
         name='password-reset-done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(  # noqa
        template_name="accounts/auth/password_reset_confirm.html"),
         name='password-reset-confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/auth/password_reset_complete.html'),
         name='password_reset_complete'),
    
    
        
]

urlpatterns += static(settings.MEDIA_URL,
 document_root=settings.MEDIA_ROOT)

Django Project/appSale/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.conf import settings

class housesale(models.Model):
    housesale_ID = models.IntegerField(primary_key = True)
    housesale_title = models.CharField(max_length=30) 
    housesale_description= models.CharField(max_length=250)
    housesale_image= models.ImageField(upload_to='house',null=True,blank=True)
    def __str__(self):
        return self.housesale_title


class Users(models.Model):
   User_ID = models.IntegerField(primary_key = True)
   User_Name = models.CharField(max_length=20)
   User_LastName = models.CharField(max_length=20)  
   User_Mail = models.EmailField(max_length = 254)
   User_Date= models.DateField()

   def __str__(self):
        return self.User_Mail


class Price(models.Model):
   Price_ID = models.IntegerField(primary_key = True)
   Price_Number = models.CharField(max_length=20)
   Price_Special = models.CharField(max_length=20)  
   Price_Money= models.CharField(max_length=50) 
   Price_Line1= models.CharField(max_length=50) 
   Price_Line2= models.CharField(max_length=50) 
   Price_Line3= models.CharField(max_length=50) 
   Price_Line4= models.CharField(max_length=50) 
   Price_Line5= models.CharField(max_length=50) 
   Price_Line6= models.CharField(max_length=50) 
   Price_URL = models.CharField(max_length = 200)

   def __str__(self):
        return self.Price_Special
    

class ContactForm(models.Model):
    contact_name=models.CharField(max_length=200)
    contact_email=models.EmailField()
    contact_phone=models.CharField(max_length=200)
    contact_messages=models.TextField()
    
    def __str__(self):
      return self.contact_name



   
class Realtor_Menu(models.Model):
   Realtor_ID = models.IntegerField(primary_key = True)
   Realtor_Name = models.CharField(max_length=200)
   user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
   Realtor_Photo =  models.ImageField(upload_to=None, height_field=None, width_field=None, max_length=100)
   
   Realtor_Line1= models.CharField(max_length=1500) 
   Realtor_Line2= models.CharField(max_length=200) 
   Realtor_Line3= models.CharField(max_length=200) 
   Realtor_URL = models.CharField(max_length = 200)

   def __str__(self):
        return self.Realtor_Name
    
    
class House_Category(models.Model):
   House_Category_ID = models.IntegerField(primary_key = True)
   HouseType = models.CharField(max_length=20)
   def __str__(self):
        return self.HouseType
    
    



# ================================================================== >> COUNTRY
class Country(models.Model):
    """Country Model."""

    name = models.CharField(
        max_length=150, null=False, blank=False, unique=True)

    shortcut = models.CharField(
        max_length=3, null=False, blank=False, verbose_name="ISO 3166-α2")

    class Meta:
        verbose_name = _("Country")
        verbose_name_plural = _("Countries")

    def __str__(self):
        return f'{self.name}'



# ==================================================================== >> STATE
class State(models.Model):
    """State Model.
    Example:
        country_id      1 - Germany
        name            Berlin
    """

    country = models.ForeignKey(Country, null=False, on_delete=models.CASCADE,
                                verbose_name=_("Country"))
    name = models.CharField(max_length=150, blank=False, null=False,
                            verbose_name=_("Country"))
    shortcut = models.CharField(
        max_length=6, null=False, blank=False, verbose_name="ISO 3166-2")

    class Meta:
        unique_together = ('country', 'shortcut')
        verbose_name = _("State")
        verbose_name_plural = _("States")

    def __str__(self):
        return (f"{self.name} - {self.country.name}")



# ================================================================== >> ADDRESS
class Address(models.Model):
    """Address Model."""
    street = models.CharField(max_length=150, blank=False, null=False,
                              verbose_name=_("Street"))
    hn = models.CharField(max_length=15, blank=False, null=False,
                          verbose_name=_("House number"))
    zipcode = models.CharField(max_length=5, blank=False, null=False,
                               verbose_name=_("Zipcode"))
    city = models.CharField(max_length=100, blank=False, null=False,
                            verbose_name=_("City"))
    state = models.ForeignKey(
        State, blank=False, null=False, on_delete=models.CASCADE,
        verbose_name=_("State"))


    class Meta:
        unique_together = ('street', 'hn', 'zipcode')
        verbose_name_plural = _("Addresses")

    def __str__(self):
        return (f"{self.street} {self.hn}, {self.city}"
                f" - {self.state.country.shortcut}")

    def get_listings(self):
        return self.street

Django Project/documents/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


# ============================================================= >> LISTING FILE
class ListingFile(models.Model):
    listing = models.ForeignKey('listings.Listing', default=None,
                                on_delete=models.DO_NOTHING,
                                verbose_name=_("Listing"))
    name = models.CharField(max_length=255,
                            verbose_name=_("Name"))
    short_description = models.CharField(max_length=255,
                                         verbose_name=_("Short description"))
    file = models.FileField(default=None, upload_to='listings/files/',
                            verbose_name=_("File"))
    created = models.DateTimeField(auto_now_add=True,
                                   verbose_name=_("Created"))
    updated = models.DateTimeField(auto_now=True, null=True,
                                   verbose_name=_("Updated"))
    for_customer = models.BooleanField(default=True,
                                       verbose_name=_("For customers"))

    def __str__(self):
        return (f"{self.listing.title}")

    def get_listing_title(self):
        return self.listing.title
    get_listing_title.short_description = _("Listing")

Django Project/appSale/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django.utils.translation import gettext_lazy as _

Django Project/appSale/views.py
from re import search
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.urls import path,include
from appSale.models import housesale,Users,Price,House_Category,Realtor_Menu,ContactForm
from django.contrib.auth.decorators import login_required
from django.views.generic import (TemplateView)
from django.utils.translation import gettext_lazy as _

from appSale.models import State
from listings.models import Listing, ListingType
from accounts.models import Realtor



# def index(request):
#   house=housesale.objects.all()
#   price=Price.objects.all() 

  
#   return render(request, 'index.html',{'house':house,'price':price}) 


def index(request):
  listings=Listing.objects.order_by('-created').filter(is_published=True)[:9]
  states=State.objects.all()
  list_types=ListingType.objects.all()
  price=Price.objects.all() 
  realtor_menu=Realtor_Menu.objects.all()

  
  return render(request, 'index.html',{'listings':listings,'states':states,'list_types':list_types,'price':price,'realtor_menu':realtor_menu}) 







class indexList(TemplateView):
    template_name = 'templates/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['listings'] = Listing.objects.order_by('-created').filter(
                               is_published=True)[:3]
        context['states'] = State.objects.all()
        context['list_types'] = ListingType.objects.all()
        context['index'] = True
        # SEO
        context['page_title'] = _("Real estate manager."
                                  " Renting, buying and selling.")
        context['page_description'] = _("Real estate manager. We offer"
                                        " real estate objects and takes care"
                                        " of every aspect for you. Services"
                                        " offered: renting, selling, buying,"
                                        " consultation and way more.")
        return context




def about(request):
  return render(request, 'about.html')

def subscribe(request):
  return render(request, 'subscribe.html')
def house(request):
  house=housesale.objects.all()
  return render(request, 'house.html',{'house':house})
def price(request):
  price=Price.objects.all()
  return render(request, 'price.html',{'price':price})

def contact(request):
      if request.method == 'POST':
        contact=ContactForm()
        c_name = request.POST.get('c_name')
        c_email = request.POST.get('c_email')
        c_phone = request.POST.get('c_phone')
        c_message = request.POST.get('c_message')
        a1=('contact.html')
        a2=('email.html')
        contact.contact_name=c_name
        contact.contact_email=c_email
        contact.contact_phone=c_phone
        contact.contact_messages=c_message
        contact.save()
        

      return render(request, 'contact.html')
    

    


@login_required(login_url="/login/")

# def home(request):  
#     searchTerm = request.GET.get('searchMovie')
#     return render(request, 'home.html',{'searchTerm':searchTerm})

def signup(request):
    email = request.GET.get('email')
    return render(request, 'signup.html', {'email':email})


# Create your views here.

Django Project/documents/views.py
from django.utils.translation import gettext_lazy as _
from django.views.generic import (DetailView, TemplateView)
from django.utils.html import format_html

from listings.models import Listing
from contacts.models import Contact


class UserDocumentView(DetailView):
    model = Listing
    template_name = 'documents/documents.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['contact'] = Contact.objects.get(listing_id=self.object.id,
                                                 user_id=self.request.user.id)
        # Showcase Section Infos
        context['title'] = _("Documents")
        context['subtitle'] = _("Manage your own documents")
        # SEO
        context['page_title'] = _("User documents")
        context['page_description'] = _("Real estate manager."
                                        "Here you can upload and manage your "
                                        "own documents")
        return context


class ListingDocumentView(TemplateView):
    template_name = 'documents/user-documents.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['docs'] = True
        # Showcase Section Infos
        context['title'] = self.object.listing.title
        context['subtitle'] = format_html(f'<i class="fas fa-map-marker"></i>'
                                          f' {self.object.listing.address}')
        # SEO
        context['page_title'] = _("Documents")
        context['page_description'] = _("Real estate manager."
                                        "Here you can manage your documents, "
                                        "related to a specific object you are "
                                        "interested in.")
        return context

Django Project/appSale/templates/documents/documents.html
{% extends 'core/base.html' %}
{% load static %}
{% load i18n %}
{% load filters %}
{% load humanize %}


{% block content %}
<section id="showcase-inner" class="py-5 text-white">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-12">
        <h1 class="display-4">{{ _("Documents for") }} {{ listing.title }}</h1>
        <p class="lead">
          <i class="fas fa-map-marker"></i> {{ listing.address.city }}, {{ listing.address.state }},
          {{ listing.address.zipcode }}</p>
      </div>
    </div>
  </div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
  <div class="container">
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'index' %}">{{ _("Home") }}</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{% url 'dashboard' %}">{{ _("Dashboard") }}</a>
        </li>

        <li class="breadcrumb-item active">{{ _("Documents") }}</li>

        <li class="breadcrumb-item">
          <a href="{% url 'listing' listing.id %}">{{ listing.title }}</a></li>
      </ol>
    </nav>
  </div>
</section>

<!-- Alerts -->
{% include 'core/partials/_alerts.html' %}

<!-- Listing -->
<section id="listing" class="py-4">
  <div class="container">
    <a href="{% url 'listing' listing.id %}" class="btn btn-light mb-4 ml-0">{{ _("Back To Listing") }}</a>


    <div class="row">
      <div class="row col-md-9 mb-5">
        <!-- Home File Liset -->

        {% if object.listingfile_set.all.count > 0 %}
        {% for document in object.listingfile_set.all %}
        {% if document.for_customer %}
        <div class="col-12">

          <h4>{{ document.name }}</h4>
          <p>{{ document.short_description }}</p>
          <!--embed src="{% static 'img/pdf.png' %}" width="40px" height="40px" /-->
          <a href="{{ document.file.url }}" target="_blank" class="btn btn-danger snice-red">
            Open File
          </a>
          <a href="{{ document.file.url }}" target="_blank" class="btn btn-danger" download>
            Download
          </a>
          <hr>
        </div>
        {% endif %}
        {% endfor %}
        {% else %}
        <div class="col-12 col-sm-6">
          <h5 class="p-2">{{ _("Nothing to display") }}.</h5>
        </div>

        {% endif %}
      </div>
      {% include 'contacts/_partials/_realtor-contact-box.html' %}
    </div>
  </div>
</section>


{% endblock %}

Django Project/appSale/templates/documents/user-documents.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block extrastyle %}
<meta name="description" content="Real estate manager.
    You can manage your object related documents here." />
{% endblock %}

{% block title %} | Profile {% endblock %}

{% block content %}
<section id="showcase-inner" class="py-5 showcase-text">
  <div class="container bg-blur">
    <div class="row">
      <div class="col-md-12 my-5">
        <h1 class="display-4 my-5 showcase-text">
          {{ title }}
        </h1>
        <p class="lead">{{ subtitle }}</p>
      </div>
    </div>
  </div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
  <div class="container">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'index' %}">
            <i class="fas fa-home"></i> {{ _("Home") }}</a>
        </li>
        <li class="breadcrumb-item"> {{ _("Profile") }}</li>
        <li class="breadcrumb-item active"> {{ _("Documents") }}</li>

      </ol>
    </nav>
  </div>
</section>

<!-- Alerts -->
{% include 'core/partials/_alerts.html' %}

<section id="dashboard" class="py-4">
  <div class="container">

    {% include 'accounts/_partials/profile-navbar.html' %}

  </div>
  </div>
</section>
{% endblock %}